### ISSUE TITLE
JSON responses contain superfluous backslashes

### ISSUE THREAD

**Issue by atomsymbol** [vayamos-exchange/api-docs#1]
ASCII **forward**-slash character (`/`) does not need a `C`-style escape sequence. For example, the **back**-slashes (`\`) in the follow snippet are redundant:

````
(https://api.vayamos.cc/spot/markets_ex)
....
"pair": "BPX\/USDT",
"base": "BPX",
"quote": "USDT",
"icon_url": "\/ico\/bpx.svg",
....
````

Or, if there is some other valid reason for using `\/` in the JSON strings, then the reason should be clearly explained at start of `README.md`.

**Comment by vayamos-exchange** [comment]
We fixed it, thanks for reporting
