### ISSUE TITLE
/spot/orderbook performance issues

### ISSUE THREAD

**Issue by atomsymbol** [vayamos-exchange/api-docs#2]
It takes up to 5 seconds to get a `/spot/orderbook` query response, even in case the the number of "asks" and "bids" in the returned JSON is zero.

**Comment by vayamos-exchange** [comment]
Hi.

The average response time with a home Internet connection is 0.2s.
Probably a problem occurs on your local side.
Check your Ping to the API server.

`$ for i in {1..100}; do time curl -X POST https://api.vayamos.cc/spot/orderbook -H 'Content-Type: application/json' -d '{"pair": "BPX/USDT"}' -o /dev/null -s; done

real    0m0.257s
user    0m0.036s
sys     0m0.000s

real    0m0.391s
user    0m0.029s
sys     0m0.010s

real    0m0.212s
user    0m0.026s
sys     0m0.009s

real    0m0.243s
user    0m0.032s
sys     0m0.001s

real    0m0.215s
user    0m0.029s
sys     0m0.005s

real    0m0.585s
user    0m0.018s
sys     0m0.015s

real    0m0.397s
user    0m0.022s
sys     0m0.019s

real    0m0.231s
user    0m0.034s
sys     0m0.001s

real    0m0.221s
user    0m0.020s
sys     0m0.013s

real    0m0.215s
user    0m0.028s
sys     0m0.012s

real    0m0.213s
user    0m0.017s
sys     0m0.017s

real    0m0.398s
user    0m0.034s
sys     0m0.000s

real    0m0.245s
user    0m0.029s
sys     0m0.006s

real    0m0.213s
user    0m0.016s
sys     0m0.020s

real    0m0.231s
user    0m0.024s
sys     0m0.012s

real    0m0.215s
user    0m0.026s
sys     0m0.009s

real    0m0.208s
user    0m0.020s
sys     0m0.018s

real    0m0.260s
user    0m0.029s
sys     0m0.005s

real    0m0.236s
user    0m0.024s
sys     0m0.011s

real    0m0.238s
user    0m0.015s
sys     0m0.020s

real    0m0.248s
user    0m0.027s
sys     0m0.009s

real    0m0.235s
user    0m0.033s
sys     0m0.000s

real    0m0.235s
user    0m0.024s
sys     0m0.007s

real    0m0.240s
user    0m0.019s
sys     0m0.012s

real    0m0.214s
user    0m0.023s
sys     0m0.004s

real    0m0.231s
user    0m0.023s
sys     0m0.010s

real    0m0.237s
user    0m0.030s
sys     0m0.004s

real    0m0.245s
user    0m0.027s
sys     0m0.008s

real    0m0.394s
user    0m0.029s
sys     0m0.005s

real    0m0.249s
user    0m0.022s
sys     0m0.008s

real    0m0.228s
user    0m0.029s
sys     0m0.005s

real    0m0.254s
user    0m0.027s
sys     0m0.008s

real    0m0.237s
user    0m0.031s
sys     0m0.004s

real    0m0.230s
user    0m0.022s
sys     0m0.011s

real    0m0.238s
user    0m0.022s
sys     0m0.011s

real    0m0.631s
user    0m0.028s
sys     0m0.008s

real    0m0.250s
user    0m0.024s
sys     0m0.012s

real    0m0.253s
user    0m0.028s
sys     0m0.004s

real    0m0.228s
user    0m0.030s
sys     0m0.004s

real    0m0.240s
user    0m0.029s
sys     0m0.000s

real    0m0.248s
user    0m0.026s
sys     0m0.004s

real    0m0.231s
user    0m0.017s
sys     0m0.014s

real    0m0.220s
user    0m0.017s
sys     0m0.020s

real    0m0.260s
user    0m0.028s
sys     0m0.008s

real    0m0.250s
user    0m0.020s
sys     0m0.012s

real    0m0.233s
user    0m0.026s
sys     0m0.009s

real    0m0.243s
user    0m0.026s
sys     0m0.013s

real    0m0.234s
user    0m0.021s
sys     0m0.011s

real    0m0.242s
user    0m0.027s
sys     0m0.010s

real    0m0.238s
user    0m0.025s
sys     0m0.007s

real    0m0.240s
user    0m0.027s
sys     0m0.010s

real    0m0.241s
user    0m0.008s
sys     0m0.022s

real    0m0.242s
user    0m0.016s
sys     0m0.017s

real    0m0.248s
user    0m0.023s
sys     0m0.014s

real    0m0.240s
user    0m0.027s
sys     0m0.008s

real    0m0.231s
user    0m0.026s
sys     0m0.005s

real    0m0.360s
user    0m0.023s
sys     0m0.012s

real    0m0.238s
user    0m0.021s
sys     0m0.011s

real    0m0.219s
user    0m0.038s
sys     0m0.000s

real    0m0.223s
user    0m0.017s
sys     0m0.012s

real    0m0.241s
user    0m0.023s
sys     0m0.012s

real    0m0.237s
user    0m0.027s
sys     0m0.008s

real    0m0.249s
user    0m0.020s
sys     0m0.016s

real    0m0.233s
user    0m0.026s
sys     0m0.008s

real    0m0.239s
user    0m0.031s
sys     0m0.005s

real    0m0.202s
user    0m0.019s
sys     0m0.010s

real    0m0.238s
user    0m0.029s
sys     0m0.005s

real    0m0.209s
user    0m0.024s
sys     0m0.008s

real    0m0.226s
user    0m0.029s
sys     0m0.005s

real    0m0.203s
user    0m0.017s
sys     0m0.011s

real    0m0.245s
user    0m0.024s
sys     0m0.005s

real    0m0.222s
user    0m0.019s
sys     0m0.016s

real    0m0.269s
user    0m0.016s
sys     0m0.017s

real    0m0.225s
user    0m0.022s
sys     0m0.007s

real    0m0.218s
user    0m0.026s
sys     0m0.007s

real    0m0.230s
user    0m0.017s
sys     0m0.017s

real    0m0.219s
user    0m0.031s
sys     0m0.006s

real    0m0.213s
user    0m0.029s
sys     0m0.009s

real    0m0.240s
user    0m0.033s
sys     0m0.001s

real    0m0.219s
user    0m0.024s
sys     0m0.010s

real    0m0.219s
user    0m0.019s
sys     0m0.012s

real    0m0.241s
user    0m0.022s
sys     0m0.011s

real    0m0.239s
user    0m0.016s
sys     0m0.015s

real    0m0.241s
user    0m0.022s
sys     0m0.010s

real    0m0.238s
user    0m0.021s
sys     0m0.011s

real    0m0.224s
user    0m0.029s
sys     0m0.008s

real    0m0.220s
user    0m0.029s
sys     0m0.004s

real    0m0.240s
user    0m0.023s
sys     0m0.012s

real    0m0.237s
user    0m0.026s
sys     0m0.009s

real    0m0.224s
user    0m0.028s
sys     0m0.004s

real    0m0.215s
user    0m0.020s
sys     0m0.010s

real    0m0.241s
user    0m0.020s
sys     0m0.006s

real    0m0.241s
user    0m0.024s
sys     0m0.009s

real    0m0.246s
user    0m0.031s
sys     0m0.001s

real    0m0.229s
user    0m0.022s
sys     0m0.008s

real    0m0.248s
user    0m0.031s
sys     0m0.004s

real    0m0.270s
user    0m0.025s
sys     0m0.009s

real    0m0.209s
user    0m0.023s
sys     0m0.012s

real    0m0.239s
user    0m0.025s
sys     0m0.015s

real    0m0.246s
user    0m0.026s
sys     0m0.005s`

**Comment by atomsymbol** [comment]
@vayamos-exchange Well, but I am using a programming language in which it is fairly easy to post multiple requests to `/spot/orderbook` concurrently. Please see #3.
